### ISSUE TITLE
Terraform configuration and continuous deployment

### ISSUE THREAD

**Issue by ndmckinley** [seattle-uat/universal-application-tool#10]
Create a terraform config and continuous deployment (evaluate Terraform Cloud?  GitHub Actions may be suitable for this as well, which would help keep all config in one place).

**Comment by ndmckinley** [comment]
In the short term, a minimal deployment on GCP, with the strong requirement that we plan to migrate to whatever cloud provider the city chooses.

**Comment by syntapy** [comment]
Hi. Kinda new to infrastructure here. Is this a correct way to approach the gcp deployment?
- Github action to push docker image to gcr
- Github action to push terraform config to terraform cloud
    - `google_cloud_run_service` to run the containers

Could I give this a shot?

**Comment by ndmckinley** [comment]
That would be a good way to do it - you'd also want a google cloud build to get the docker containers built on submit, and a postgres database.

I notice you're not a collaborator on the repo - are you a city employee or an interested third party?  We can chat on one of the internal platforms if you are on the city's domain, or we can discuss here if not.

**Comment by syntapy** [comment]
Ok, I'll try to make sense of that, thanks!

Yeah I would be classified as an interested 3rd party...not an employee in Seattle

**Comment by ndmckinley** [comment]
Hey there @syntapy!

Taking a look at your branch it looks like things are going exactly right - you may want to rebase on main, since there's a new dockerfile (formatter.Dockerfile) that you might also move into your docker/ folder (which I think is a fine way of organizing it).

I'd also suggest not making adminer available on cloud run - not sure it's needed / useful now that we're managing the db with ebeans and evolutions.

@hmhsu - is `adminer` still needed?

Also, we heard back from the city - AWS is going to be the target eventually, but GCP will be a useful stopgap while we wait for access to AWS accounts.

Thanks for your help!

**Comment by hmhsu** [comment]
Re `adminer`:

Happy for that to be removed. It was useful when we were verifying connection from the app to the database. I think we are all good now.

**Comment by ndmckinley** [comment]
@syntapy hey there!

We have actually just gotten access to the AWS account we need, actually.  We're going to start work on the AWS prod environment.  I think that obsoletes your work, unfortunately.

**Comment by syntapy** [comment]
Ok. Well I definitely had some fun in the process, though haven't gotten the google_cloud_run_service to work though. I'll play with that some more sometimes to see what was wrong with it

Have fun with the AWS prod work!
