### ISSUE TITLE
Admin can view block dashboard for a program

### ISSUE THREAD

**Issue by bion** [seattle-uat/universal-application-tool#107]
**Additional context**
3 panel layout:
- left is list of block titles that link to each block
- center is current block with its details and questions
- right is question bank as an independently scrolling list

See https://tiny.cc/uat-flow for lightweight mock.

**Done when**
Admin can view block dashboard for a program

**Comment by lianne-oy** [comment]
M1 Review - In progress

**Comment by kendrickt** [comment]
Closed by https://github.com/seattle-uat/universal-application-tool/pull/288
