### ISSUE TITLE
Admin can view block form

### ISSUE THREAD

**Issue by bion** [seattle-uat/universal-application-tool#108]
Block form only has one input, block title, for now

**Additional context**
Admin can reach the block form by clicking "new block" from program block dashboard

See https://tiny.cc/uat-flow for lightweight mock.

**Done when**
Admin can view the form

**Comment by lianne-oy** [comment]
M1 Review - In progress

**Comment by kendrickt** [comment]
Closed by https://github.com/seattle-uat/universal-application-tool/pull/288
