### ISSUE TITLE
Admin can remove a question from a block using block dashboard

### ISSUE THREAD

**Issue by bion** [seattle-uat/universal-application-tool#111]
blocked on #110 

**Describe the solution you'd like**
In block dashboard center panel is current block with list of questions in the block. Each question has a checkbox next to it. Single "Remove from Block" button removes the checked questions from the block.

See https://tiny.cc/uat-flow for lightweight UI mock.

**Done when**
Admin can remove a question from a block using block dashboard

**Comment by gcapiel** [comment]
wireframes : https://miro.com/app/board/o9J_lXULxwE=/?moveToWidget=3074457354358891906&cot=14

**Comment by lianne-oy** [comment]
M1 Review - In progress
