### ISSUE TITLE
Applicant can view list of programs

### ISSUE THREAD

**Issue by bion** [seattle-uat/universal-application-tool#112]
**Describe the solution you'd like**
Simple list displaying the names of the `ProgramDefinition`s in the system.

**Done when**
Applicant can view list of programs

**Comment by gcapiel** [comment]
wireframes: https://miro.com/app/board/o9J_lXULxwE=/?moveToWidget=3074457354363151327&cot=14

**Comment by lianne-oy** [comment]
M1 Review - In progress

**Comment by carolinedanzi** [comment]
https://github.com/seattle-uat/universal-application-tool/issues/112 fixes
