### ISSUE TITLE
Selection of first City Program for pilot

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/universal-application-tool#123]

**Comment by neel-a-mehta** [comment]
Someone from the city said that this program (Senior Farmers Market Nutrition Program) might be interested.

https://www.dshs.wa.gov/altsa/home-and-community-services/senior-farmers-market-nutrition-program

However, it seems to be administered at the state level, not the city.

**Comment by neel-a-mehta** [comment]
Sounds like we're thinking of:

- Car Tab Rebate Program
- Parks & Rec After School Care / Summer Camp
- Utility Discount Program?
- DEEL something?

Not sure what the best one here is.

**Comment by neel-a-mehta** [comment]
Here's the criteria we're thinking about...

https://seattlegov.sharepoint.com/:p:/r/sites/IAC-EXT/AP/_layouts/15/Doc.aspx?sourcedoc=%7B8981F87F-C06F-4326-AFA1-28DD312C7ED2%7D&file=UAT%20Weekly%20Status%20Update%20with%20City%20of%20Seattle.pptx&action=edit&mobileredirect=true&wdPreviousSession=6f3f1207-c000-4464-bb98-6c45cb6d32e7&wdOrigin=TEAMS-WEB.customspo.undefined&cid=588a5e16-2fd4-44b4-a2ed-b62913329434

**Comment by lianne-oy** [comment]
DEEL selected.
