### ISSUE TITLE
Define how form version control (if any) would work

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/universal-application-tool#128]
Is it visible to the user? Should they be able to have multiple draft copies of the form handy?

**Comment by neel-a-mehta** [comment]
Gerardo and I were just discussing -- it would be best to have a "linear" approach where there's one "live" version of the form, and the user can hit "publish" at any time to update the live version to their draft version. Webflow and Qualtrics do it exactly like this. So no branching or anything, but at least you can stage a draft version before you release it to the world. 

See wireframes:
https://miro.com/app/board/o9J_lXULxwE=/?moveToWidget=3074457354352312206&cot=14

**Comment by gcapiel** [comment]
For now my thoughts are we keep the front end simple. Version control will mainly be used to protect accidental changes to the currently live/published version.  From a UI standpoint, a version will not be made live for applicants until the UAT admin presses the [publish button](https://miro.com/app/board/o9J_lXULxwE=/?moveToWidget=3074457354356345961&cot=14) on a program.  The UAT admin will also be able to [preview](https://miro.com/app/board/o9J_lXULxwE=/?moveToWidget=3074457354362597164&cot=14) an unpublished version.

**Comment by neel-a-mehta** [comment]
As an example, Webflow follows a similar model, where you can have draft & live versions of your site. You can publish (which makes your live version equal to a snapshot of your latest draft version) at any time.

![image](https://user-images.githubusercontent.com/77128518/108241538-f09eeb80-7119-11eb-8871-86b4dc06553d.png)


Webflow also lets you toggle between the draft and live preview mode with the eye button in the top left, like so:

![image](https://user-images.githubusercontent.com/77128518/108241393-c9e0b500-7119-11eb-8b74-9a8882486eb0.png)

**Comment by bion** [comment]
Something to bear in mind with versioning is that an applicant's application must be pinned to a specific version once they start. For them to see the next version we'll need to define a expiration time for their previous application (maybe 10 months? maybe it's admin-configurable?).

A follow-on feature should be automated migration of data from the previous application to the next one.

Since we know that the city generally updates most of their forms about once a year, I don't expect this behavior to be of too much concern.

**Comment by neel-a-mehta** [comment]
Hey @bion, @gcapiel was wondering: what happens when you edit a question for a form that's already live? Does that form use the old version of the question, or update to use the new one?

**Comment by bion** [comment]
@neel-a-mehta, @gcapiel  The entire configuration set is locked on published. To make changes the admin creates a new version.

**Comment by neel-a-mehta** [comment]
See also [Bion's versioning doc](https://teams.microsoft.com/_?tenantId=78e61e45-6beb-4009-8f99-359d8b54f41b#/docx/viewer/customspo/https:~2F~2Fseattlegov.sharepoint.com~2Fsites~2FIAC-EXT~2FAP~2FShared%20Documents~2FProject%203-%20Google.org~2FProject%20docs~2FEngineering~2FVersioning%20system%20overview.docx?threadId=19:23610255e0b841ac8464c1ad04dc7639@thread.tacv2&baseUrl=https:~2F~2Fseattlegov.sharepoint.com~2Fsites~2FIAC-EXT~2FAP&fileId=0E977791-EE18-4B68-BF95-BE2FDA8030B9&viewerAction=view)

**Comment by neel-a-mehta** [comment]
Between that doc and stuff on tiny.cc/uat-flow, I think we've defined this well enough from the product/UX side.
