### ISSUE TITLE
Create user account and Applicant for unauth'd visitors

### ISSUE THREAD

**Issue by natsid** [seattle-uat/universal-application-tool#170]
A user account should automatically and silently be created when an unauthorized visitor visits a page that requires auth. In the context of the "applicant" user role, an associated `Applicant` (with foreign key to the new user/profile) should also be created.

**Done when**
There exists a way to silently create a user account and associated applicant, likely by using the `@Secure` annotation.

**Comment by lianne-oy** [comment]
M1 Review - In progress
