### ISSUE TITLE
Implement a .equals() method for QuestionDefinition

### ISSUE THREAD

**Issue by carolinedanzi** [seattle-uat/universal-application-tool#196]
**Is your feature request related to a problem? Please describe.**
Testing QuestionDefinition equality in unit tests is annoying, since there is no `.equals()` method override

**Describe the solution you'd like**
Override `.equals()` in QuestionDefinition and update current unit tests to use this for equality checks

**Done when**
Unit tests use `assertThat().isEqualTo()` for QuestionDefinitions

**Comment by carolinedanzi** [comment]
Putting this on pause for now - we're rethinking the QuestionDefinition classes, and having subtypes complicates things. .equals is a nice-to-have

**Comment by lianne-oy** [comment]
M1 Review - Not worked on currently
