### ISSUE TITLE
Introduce different user roles (applicant, Program Admin, TI)

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/universal-application-tool#204]
As of Milestone 1, everyone is assigned the UAT Admin role. Start differentiating into other roles.

**Comment by ndmckinley** [comment]
#223 gets us most of the way there - once we have pages where the roles are significant, this will be done.

**Comment by lianne-oy** [comment]
Identity-related issues in M3 will cover any remaining open items on this one.
