### ISSUE TITLE
Figure out how the UAT connects to affordableseattle.org

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/universal-application-tool#285]
Do we add a button to the affordableseattle.org homepage? Do we replace the "apply now" buttons on the search result page with deep-links to the UAT?

**Comment by neel-a-mehta** [comment]
cc @lianne-oy @jakejwright @gcapiel

**Comment by neel-a-mehta** [comment]
https://docs.google.com/presentation/d/1NH7uxCCSKKeVwDjUR1S6zbg9NaAJPy4caVe1m4KdHzQ/edit#slide=id.p

**Comment by lianne-oy** [comment]
Had a few discussions last week on this, where we made decisions.  Marking as closed and will create separate launch task for rollout.
