### ISSUE TITLE
Set up Sass stylesheets

### ISSUE THREAD

**Issue by natsid** [seattle-uat/universal-application-tool#38]
We'll use [Sass](https://sass-lang.com/) for our stylesheets.

Based on [this reference for community plugins](https://www.scala-sbt.org/1.x/docs/Community-Plugins.html#Web+and+frontend+development+plugins), we probably want to include the [sbt-puresass](https://chiselapp.com/user/twenstar/repository/sbt-puresass/index) and [sbt-web](https://github.com/sbt/sbt-web) plugins.

Done when we can serve a page styled with Sass.

**Comment by natsid** [comment]
Looks like the puresass plugin won't work on the more recent version of sbt we're on. Trying the plugin mentioned in https://www.playframework.com/documentation/2.8.x/AssetsSass instead.

**Comment by carolinedanzi** [comment]
Thanks Natalie! Just wanted to add a note that we'll need to be careful naming files - if there are two files with the same name/path below stylesheets/ in `public/stylesheets` and our `assets/stylesheets`, they will conflict
