### ISSUE TITLE
Fix slow first request to dev server

### ISSUE THREAD

**Issue by bion** [seattle-uat/universal-application-tool#46]
The development server takes quite a while to serve its first response because it waits to compile until it's received its first request. Investigate the cause of this and find a solution that either reduces the compilation time or does it on initial server start and gets it out of the way.

Done when: serving the first request request does not require waiting for recompilation

**Comment by hmhsu** [comment]
There doesn't seem to be an easy config change to fix this, or at least I haven't found one.

See this [Stackoverflow question](https://stackoverflow.com/questions/50802075/play-framework-slow-at-first-call). The given answer is to write a warmup task that automatically sends a request to server upon startup. That works but is not an elegant fix.

**Comment by ndmckinley** [comment]
Yeah, I'm just gonna close this.  All we could really do is make the compilation happen before the server starts, which would at best be the same and at worst add time.
