### ISSUE TITLE
CloudFormation template + config

### ISSUE THREAD

**Issue by ndmckinley** [seattle-uat/universal-application-tool#62]

**Comment by syntapy** [comment]
Is this gonna be done using ecs / eks? I got something deployed on ecs last night with terraform, but I'm down to give it a shot on cloudformation over the next couple days if thats OK with you all

**Comment by ndmckinley** [comment]
Hey, thanks for volunteering, but sorry - we're already working on this one!

**Comment by ndmckinley** [comment]
It definitely is, though - if you have any advice we'd love to hear it once it's in, we'll be doing it iteratively.

**Comment by syntapy** [comment]
Well, yall are more than welcome to take my advice so long as no one blames me when of a sudden all the servers start intermittently crashing and accidentally corrupting applicant data, oh I dunno, by sporadically changing the species column to random values or something XD

**Comment by syntapy** [comment]
Well, yall are more than welcome to take my advice so long as no one blames me when stuff goes wrong XD
