### ISSUE TITLE
All users can see a list of programs

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/universal-application-tool#76]
Includes:

- Database stores list of programs
- UI renders this list

**Comment by gcapiel** [comment]
wireframes : https://miro.com/app/board/o9J_lXULxwE=/?moveToWidget=3074457354355841621&cot=14

**Comment by neel-a-mehta** [comment]
#106 ensures that the admin can see this, and that one appears done. But I don't know if this works for the other user groups.

**Comment by lianne-oy** [comment]
M1 Review - Complete.  Still working on other roles.  Then changing behavior next.
