### ISSUE TITLE
Admin can define form with single question (using Text widget)

### ISSUE THREAD

**Issue by lianne-oy** [seattle-uat/universal-application-tool#83]
- Does not need to be with UI; can be hardcoded for now

**Comment by neel-a-mehta** [comment]
#95 includes this.

**Comment by gcapiel** [comment]
wireframes : https://miro.com/app/board/o9J_lXULxwE=/?moveToWidget=3074457354355841620&cot=14

**Comment by lianne-oy** [comment]
M1 Review - In progress
