### ISSUE TITLE
UAT Admin can build a question with the Text type

### ISSUE THREAD

**Issue by lianne-oy** [seattle-uat/universal-application-tool#85]
- Question Builder UI not necessary yet; can be hardcoded

**Comment by neel-a-mehta** [comment]
#95 is the specific implementation of this story.

**Comment by gcapiel** [comment]
wireframes : https://miro.com/app/board/o9J_lXULxwE=/?moveToWidget=3074457354352415135&cot=14

**Comment by lianne-oy** [comment]
M1 Review - In progress
