### ISSUE TITLE
Integrate database with sample Play app

### ISSUE THREAD

**Issue by ndmckinley** [seattle-uat/universal-application-tool#9]
- [ ] add command in bin/ to stand up docker swarm and run some tests
- [x] connect database to play app - [link](https://www.playframework.com/documentation/2.7.x/JavaDatabase) @hmhsu 
- [ ] add basic schema management - [link](https://www.playframework.com/documentation/2.6.x/JavaEbean) @ndmckinley

**Comment by ndmckinley** [comment]
We're going to try and use `ebean` instead of `migrate`, so I'll start over on that one.

**Comment by hmhsu** [comment]
Is this done by #18 ?

**Comment by ndmckinley** [comment]
Yep!
